spring.redis.host: 115.182.74.89
spring.redis.port: 6379
spring.redis.database: 0
spring.redis.password: a77af61dd9f8e6c974b9f092032998d0
spring.data.mongodb.uri: mongodb://115.182.74.89:27017/idiomgame
spring.jpa.show-sql: true
test: mytest
logging.file: ../Dev/logs/business-kafka.log
logging.level.com.yingmoo: DEBUG
dubbo.provider.protocol.port: 20999
dubbo.provider.registry.address: zookeeper://115.182.74.89:2181
